### PR TITLE
Fix/generalise interface

### LINKED ISSUE #3: Generalise interface
Change tryConnectingToTwilio with:

/**
 * Attempts to connect to the backend with your 
 * authentication options
 * returning an authenticated client object on success.
 * this client is to be passed to other API calls.
 * 
 * @param {Object} authoptions - this backend's authentication object
 * 
 * @returns {Object} - client object to do API calls.
 */
async tryConnecting(authoptions) {}

### PR DESCRIPTION
**Pull request by tahmed4**

### CODE REVIEW

File: ubfToTwilio.js [hunk 1]
```diff
@@ -11,12 +11,12 @@ const unlinkNumber =  require("./lib/unlinkFromNumber")
 class Api {
```
Comment (Zvezdin) [inline ubfToTwilio.js:12]: is there any way we can inherit the functions from the other class?

**Review by Zvezdin — APPROVED** [review]
Check if we can do that, if it's not easy, just merge
